#!/bin/bash
CONF_DIR="$HOME/.config/tinkerfetch"

mkdir -p "$CONF_DIR"

if [[ "$1" == "--events" ]]; then
    echo -e "\e[38;5;213mFetching latest TinkerHub events...\e[0m"
    
    curl -s --max-time 5 'https://tinkerhub.org/events' | \
    perl -ne 'print $1 if /id="__NUXT_DATA__">(.*?)<\/script>/' | \
    jq -r '. as $root | def r(i): if (i|type) == "number" then $root[i] else i end; 
        [ .[] | select(type == "object" and .name != null and .startDate != null) | {n: r(.name), d: r(.startDate)} ] | 
        sort_by(.d) | .[:6] | to_entries[] | 
        .key as $idx | .value.n as $name | .value.d[:10] as $date | 
        if $idx == 0 then
            # First event: 2 spaces Left
            "\u001b[38;5;213m║\u001b[38;5;255m ▸ " + ($name[:38] | . + " " * (38 - length)) + "(\u001b[38;5;243m" + $date + "\u001b[38;5;255m) \u001b[38;5;213m║"
        else
            # Others: 2 spaces Right
            "  \u001b[38;5;213m║\u001b[38;5;255m ▸ " + ($name[:39] | . + " " * (39 - length)) + "(\u001b[38;5;243m" + $date + "\u001b[38;5;255m) \u001b[38;5;213m║"
        end' > "$CONF_DIR/events.txt"

    fastfetch --config "$CONF_DIR/events.jsonc"
else
    fastfetch --config "$CONF_DIR/config.jsonc"
fi
